global:
  scrape_interval:     5s # By default, scrape targets every 5 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  # scrape prometheus' own metrics
  - job_name: 'prometheus'

    static_configs:
      - targets: ['localhost:9090']


  # scrape metrics from the pushgateway - this is where our arduino sensors send metrics to
  - job_name: 'push-gateway'

    # allows the arduino sensors to override labels for metrics
    honor_labels: true

    static_configs:
      # this is the ip address of the docker host
      # the pushgateway container forwards port 9091 to the host, so we don't need to know the container's ip address
      - targets: ['192.168.2.10:9091']